exception: remove IllegalSquareClickException
    * This is only used in BoardDrawer, but it is never
      actually thrown, as white squares are not clickable
      anyway.